### ISSUE TITLE
c-3po updates

### ISSUE THREAD

**Issue by AlexMost** [sozialhelden/accessibility-cloud-js#1]
Hey, I see you are using c-3po for translations. It has been updated recently. Here is the docs page - https://c-3po.js.org/. 

Feel free to ask questions about translation process with c-3po - https://github.com/c-3po-org/c-3po/issues. Also feature requests and suggestions are welcome!

**Comment by opyh** [comment]
Thanks for your great work, I'm really happy with the library so far! The next version will use the up-to-date process with webpack/Babel.
